In [ ]:
# Function Transformer ------> If you waant to apply any operation (pre-defined,custom)
# we can use Function Transformer.

# FunctionTransformer(<logic_name>.transform<data>)

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create datasheet
x= np.array([[1,2],[3,4]])
print(x)
# # define the transformation function
log_transform = FunctionTransformer(np.sqrt)

# # apply the transformation to the dataset
X_transformed = log_transform.transform(x)

# # view the transformed data
print(X_transformed)

[[1 2]
 [3 4]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
# Practical Uses

# 1. Custom Feature Engineering
# Create a dataset
X = np.array([[1,2],[3,4]])

# define a custom feature engineering function
def squ(X):
  return np.hstack((X, X**2))

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(squ)

# apply the transformer to the use input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
# 2. Scalling And Normalization
# create a dataset
X = np.array([[1,2],[3,4]])

# define a custom scaling function
def my_scaling(X):
  return X / np.max(X)

# create a FunctionTransformer to apply thr custom function
custom_transformer = FunctionTransformer(my_scaling)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
# Column Transformer ----->
# Containr --------> steps of process --------->
# Transformer ---------> ('constant','Operation_Name','Column_Name')

# Dr ---> 1-1 Single Column --->
# 1-1 column ----->  Shape ----> all column shape concatenate ----> output

# column transformer -----> all column shape concatenate ---> output ---> same

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# df = pd.read_csv('/content/covid_toy.csv')
# df.head(2)

In [ ]:
# Decorator
# Decorator ----------> A design pattern that allows modifying the behavior of a function.


In [ ]:
def outerfunc(num):
  print("outer function print =>" , num)
  def innerfunc():
    print("hey inner function",num)

  return innerfunc

x=outerfunc(100)
print("x:",x)
x()

outer function print => 100
x: <function outerfunc.<locals>.innerfunc at 0x792256333240>
hey inner function 100


In [ ]:
def outerfunc(num):
    print("hhh")
    def innerfunc():
        print("hey inner function",num)
        test_r = num()                          #num() called test()
        print( test_r.upper() )
    return innerfunc

@outerfunc
def test():
    return ("test function is here")


test()

hhh
hey inner function <function test at 0x792256333a60>
TEST FUNCTION IS HERE
