Creating Array in Numpy

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# Using Linspace
arr = np.linspace(1,10,1000).reshape((10,10,10))
print(arr)

[[[ 1.          1.00900901  1.01801802  1.02702703  1.03603604
    1.04504505  1.05405405  1.06306306  1.07207207  1.08108108]
  [ 1.09009009  1.0990991   1.10810811  1.11711712  1.12612613
    1.13513514  1.14414414  1.15315315  1.16216216  1.17117117]
  [ 1.18018018  1.18918919  1.1981982   1.20720721  1.21621622
    1.22522523  1.23423423  1.24324324  1.25225225  1.26126126]
  [ 1.27027027  1.27927928  1.28828829  1.2972973   1.30630631
    1.31531532  1.32432432  1.33333333  1.34234234  1.35135135]
  [ 1.36036036  1.36936937  1.37837838  1.38738739  1.3963964
    1.40540541  1.41441441  1.42342342  1.43243243  1.44144144]
  [ 1.45045045  1.45945946  1.46846847  1.47747748  1.48648649
    1.4954955   1.5045045   1.51351351  1.52252252  1.53153153]
  [ 1.54054054  1.54954955  1.55855856  1.56756757  1.57657658
    1.58558559  1.59459459  1.6036036   1.61261261  1.62162162]
  [ 1.63063063  1.63963964  1.64864865  1.65765766  1.66666667
    1.67567568  1.68468468  1.69369369  1.7027027

In [10]:
arr = np.arange(0,1000).reshape(10,10,10)
print(arr.size)

1000


In [11]:
one_like = np.ones_like(arr)
print(one_like)

[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1

In [12]:
# Creating Zero Like Array
zero_like = np.zeros_like(arr)
print(zero_like)

[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0

In [13]:
# Empyte Like Array
empty_like = np.empty_like(arr)
print(empty_like)

[[[  2353530786736   2353530569968   2353633529798               0
                 0               0   2353633529728   2353633529797
                11               0]
  [              8               0               0               0
                 0               0               0               0
                 0               0]
  [              0               0               0               0
                 0               0               0               0
                 0               0]
  [              0               0               0               0
                 0               0               0               0
                 0               0]
  [              0               0               0               0
                 0               0               0               0
                 0               0]
  [              0               0               0               0
                 0               0               0               0
                

In [14]:
# One Matrix of (3,3)
one_matrix = np.ones((3,3))
print(one_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Zero Matrix of (3,3)
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Empty Matrix of (4,5)
empty_matrix = np.empty((4,5))
print(empty_matrix)

[[6.95301548e-310 6.95301548e-310 1.16279958e-311 1.29060870e-306
  1.16279958e-311]
 [7.56593016e-307 1.16279958e-311 1.24610723e-306 0.00000000e+000
  1.16279958e-311]
 [1.16279958e-311 1.16279958e-311 0.00000000e+000 3.24107064e-321
  4.68374232e-321]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]]


In [ ]:
# Shape
shape_matrix = np.shape((4,5))
print(arr.shape)

(5,)


In [ ]:
# Dimension
dimension_matrix = arr.ndim((4,5))
print(arr.ndim)

1


In [32]:
# Size
size_matrix = arr.size
print(arr.size)

5


In [ ]:
# Creating an array using random number
arr = np.random.rand(5)  
print(arr)

[0.47147991 0.72896552 0.48054972 0.25403741 0.66100692]


In [ ]:
#create an array using linsapce
arr = np.linspace(1, 5, 10)
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
# create an array using arange
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [34]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
li = []
for i in range(3):
    for j in range(3):
        if i == j:
            print(1, end=" ")
        else:
            print(0, end=" ")
    print()
li


1 0 0 
0 1 0 
0 0 1 


[]

In [ ]:
numbers = input().split()
numbers = list(map(int, numbers))
arr = np.array(numbers)
print(arr)


In [ ]:
# Create an array with arrange, apply cumsum, cumprod
import numpy as np
arr = np.arange(0,20).reshape(4,5)
# print(np.cumsum(arr))
print(np.cumprod(arr).reshape(4,5))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
